# Generated by Django 5.2.6 on 2026-01-29 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cashier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Aberto"), ("closed", "Fechado")],
                        default="open",
                        max_length=7,
                    ),
                ),
                (
                    "date_closing",
                    models.DateTimeField(blank=True, null=True, unique=True),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_incomes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "income_pix",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "income_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "income_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "income_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expense_pix",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expense_boleto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expense_automatic",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expense_others",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expense_withdrawal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Caixa",
                "verbose_name_plural": "Caixas",
                "ordering": ["-date_closing"],
            },
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nome"),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="CNPJ must be a valid 14-digit number ex: 01.234.567/0008-91",
                        max_length=18,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        help_text="CEP must be a valid format ex: 12345-678",
                        max_length=10,
                        null=True,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City name, ex: São Paulo",
                        max_length=100,
                        null=True,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State must be a valid 2-letter abbreviation ex: SP",
                        max_length=2,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Street name ex: Av. Paulista",
                        max_length=255,
                        null=True,
                        verbose_name="Rua",
                    ),
                ),
                (
                    "house_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Ex: 1",
                        null=True,
                        verbose_name="Numero da casa",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Jd. Santa Rosa",
                        max_length=124,
                        null=True,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number must be a valid format ex: (19) 91234-5678",
                        max_length=20,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email must be a valid email address ex: your@email.com",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "cnae_code",
                    models.CharField(
                        blank=True,
                        help_text="CNAE code must be a valid format ex: 47.11-3-01",
                        max_length=10,
                        null=True,
                        verbose_name="Código CNAE",
                    ),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        help_text="Description of the CNAE code",
                        max_length=255,
                        null=True,
                        verbose_name="Código do serviço",
                    ),
                ),
                (
                    "iss_retained",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Iss retido"
                    ),
                ),
                (
                    "iss_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Valor de iss retido",
                    ),
                ),
                (
                    "iss_aliquot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Alíquota de iss",
                    ),
                ),
                (
                    "description_service",
                    models.TextField(
                        help_text="Detailed description of the service",
                        verbose_name="Descrição do serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Installments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_installments",
                    models.IntegerField(
                        help_text="Ex. 1", verbose_name="Quantidade de Parcelas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quantidade de parcela",
                "verbose_name_plural": "quantidade de parcelas",
                "ordering": ["quantity_installments"],
            },
        ),
        migrations.CreateModel(
            name="NFSe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(auto_now_add=True, verbose_name="Data de Emissão"),
                ),
                (
                    "uuid_nfse",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="UUID da NFSe"
                    ),
                ),
                (
                    "link_pdf",
                    models.URLField(blank=True, null=True, verbose_name="Link do PDF"),
                ),
                (
                    "link_xml",
                    models.URLField(blank=True, null=True, verbose_name="Link do XML"),
                ),
                (
                    "reference_month",
                    models.CharField(
                        help_text="Format MM/YYYY",
                        max_length=7,
                        verbose_name="Mês de Referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Fiscal de Serviço Eletrônica (NFSe)",
                "verbose_name_plural": "Notas Fiscais de Serviço Eletrônicas (NFSe)",
                "ordering": ["-issue_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(max_length=100, verbose_name="método")),
                (
                    "applies_to",
                    models.CharField(
                        default="students",
                        help_text="students / all",
                        max_length=24,
                        verbose_name="Aplica-se a",
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de Pagamento",
                "verbose_name_plural": "Métodos de Pagamento",
                "ordering": ["method"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_plan",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Plano"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(verbose_name="Duração (meses)"),
                ),
            ],
            options={
                "verbose_name": "Plano",
                "verbose_name_plural": "Planos",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Serviço"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StatusBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Status da Conta",
                "verbose_name_plural": "Status das Contas",
            },
        ),
        migrations.CreateModel(
            name="TypeBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type_bill", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de Conta",
                "verbose_name_plural": "Tipos de Conta",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255, verbose_name="Conta")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="data de vencimento")),
                (
                    "appellant",
                    models.BooleanField(default=False, verbose_name="Recorrente"),
                ),
                (
                    "date_payment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do pagamento"
                    ),
                ),
                (
                    "apply_discount",
                    models.BooleanField(default=False, verbose_name="aplicar desconto"),
                ),
                (
                    "value_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor de desconto",
                    ),
                ),
                (
                    "percent_discount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem de desconto",
                    ),
                ),
                (
                    "value_fine",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor da desconmulta",
                    ),
                ),
                (
                    "percent_fine",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem da multa",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="valor",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="enterprise.cashier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta",
                "verbose_name_plural": "Contas",
                "ordering": ["-due_date", "description"],
            },
        ),
    ]
