# Generated by Django 5.2.6 on 2026-01-29 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfse",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfses",
                to="students.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enterprise.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="enterprise.statusbill",
                verbose_name="status",
            ),
        ),
    ]
