# Generated by Django 5.2.6 on 2026-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="cod_operation",
            field=models.CharField(
                blank=True,
                help_text="Código indicador de operação ex: 030101",
                max_length=10,
                null=True,
                verbose_name="Código indicador de operação",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="code_nbs",
            field=models.CharField(
                blank=True,
                help_text="Código NBS ex: 122051200",
                max_length=20,
                null=True,
                verbose_name="Código NBS",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="situation_tributary",
            field=models.CharField(
                blank=True,
                help_text="Código de situação tributária ex: 000",
                max_length=10,
                null=True,
                verbose_name="Código de situação tributária",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="tax_tributary",
            field=models.CharField(
                blank=True,
                help_text="Código de classificação tributária ex: 000001",
                max_length=10,
                null=True,
                verbose_name="Código de classificação tributária",
            ),
        ),
    ]
