# Generated by Django 5.2.6 on 2026-01-29 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        help_text="Enter the status of the student, e.g., Active, Inactive",
                        max_length=100,
                        verbose_name="Status do Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status do Aluno",
                "verbose_name_plural": "Status dos Alunos",
            },
        ),
        migrations.CreateModel(
            name="MonthlyFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_name",
                    models.CharField(
                        blank=True,
                        max_length=124,
                        null=True,
                        verbose_name="Nome do Aluno",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the monthly fee amount",
                        max_digits=10,
                        verbose_name="Valor da Mensalidade",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Enter the due date for the monthly fee",
                        verbose_name="Data de Vencimento",
                    ),
                ),
                (
                    "reference_month",
                    models.CharField(
                        help_text="Format MM/YYYY",
                        max_length=7,
                        verbose_name="Mês de Referência",
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the monthly fee has been paid",
                        verbose_name="Pago",
                    ),
                ),
                (
                    "date_paid",
                    models.DateField(
                        blank=True,
                        help_text="Enter the paid date for the monthly fee",
                        null=True,
                        verbose_name="Data que realizou o pagamento",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor de desconto",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem de desconto",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthlyfees",
                        to="enterprise.plan",
                        verbose_name="Plano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensalidade",
                "verbose_name_plural": "Mensalidades",
                "ordering": ["-created_at", "student"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(max_length=72, verbose_name="Metodo de pagamento"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor do pagamento",
                    ),
                ),
                (
                    "quantity_installments",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Quantidade de parcelas"
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="enterprise.cashier",
                    ),
                ),
                (
                    "montlhyfee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.monthlyfee",
                        verbose_name="mensalidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the full name of the student",
                        max_length=100,
                        verbose_name="Nome Completo",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True,
                        help_text="Enter a valid CPF or CNPJ number",
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Enter a valid phone number",
                        max_length=20,
                        null=True,
                        verbose_name="Número de telefone",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the student",
                        null=True,
                        verbose_name="Observação",
                    ),
                ),
                (
                    "due_date",
                    models.IntegerField(
                        blank=True,
                        help_text="Enter the due date for payments",
                        null=True,
                        verbose_name="Data de Vencimento",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Select the plan associated with the student",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="enterprise.plan",
                        verbose_name="Plano",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.statusstudent",
                        verbose_name="Status do Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["status", "name"],
            },
        ),
        migrations.AddField(
            model_name="monthlyfee",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_fees",
                to="students.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição da ação realizada",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.statusstudent",
                        verbose_name="Status do Aluno",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="students.student",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico",
                "verbose_name_plural": "Históricos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data da Frequência",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="frequencies",
                        to="students.student",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequência",
                "verbose_name_plural": "Frequências",
                "ordering": ["-attendance_date", "-created_at"],
                "unique_together": {("student", "attendance_date")},
            },
        ),
    ]
