# Generated by Django 5.2.6 on 2026-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0003_enterprise_cod_operation_enterprise_code_nbs_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="monthlyfee",
            index=models.Index(
                fields=["student", "-created_at"], name="students_mo_student_9127cd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyfee",
            constraint=models.UniqueConstraint(
                fields=("student", "reference_month", "plan"),
                name="uniq_monthlyfee_student_reference_month_plan",
            ),
        ),
    ]
